import {
  TransferEvent,
  CorrelatedIncident,
  NodeHealth,
  AnomalyScore,
  FailurePrediction,
  BaselineData,
  RootCauseCandidate,
  Alert,
  MetricCard,
  ErrorCodeDistribution,
  AccountHealth,
} from './types';

const now = new Date();
const formatISO = (date: Date) => date.toISOString();
const addMinutes = (date: Date, minutes: number) => new Date(date.getTime() + minutes * 60000);
const addHours = (date: Date, hours: number) => new Date(date.getTime() + hours * 3600000);
const addDays = (date: Date, days: number) => new Date(date.getTime() + days * 86400000);

export const mockTransfers: TransferEvent[] = [
  {
    event_id: 'st-ev-20260606-abc123',
    source: 'axway_securetransport',
    timestamp: formatISO(addMinutes(now, -5)),
    transfer_id: 'tr-98765',
    status: 'failed',
    file_name: 'inbound/payments_20260606.csv',
    file_size_bytes: 1458203,
    duration_ms: 34000,
    protocol: 'SFTP',
    source_host: 'partner-bank-01.external.com',
    target_folder: '/inbound/payments/',
    account: 'partner_bank_inc',
    error_code: 'ST-ERR-4032',
    error_message: 'SSH key authentication failed',
    node: 'st-node-03.prod',
    cluster: 'prod-us-east',
  },
  {
    event_id: 'st-ev-20260606-def456',
    source: 'axway_securetransport',
    timestamp: formatISO(addMinutes(now, -12)),
    transfer_id: 'tr-98764',
    status: 'failed',
    file_name: 'inbound/orders_20260606.xml',
    file_size_bytes: 892341,
    duration_ms: 28000,
    protocol: 'SFTP',
    source_host: 'partner-bank-01.external.com',
    target_folder: '/inbound/orders/',
    account: 'partner_bank_inc',
    error_code: 'ST-ERR-4032',
    error_message: 'SSH key authentication failed',
    node: 'st-node-03.prod',
    cluster: 'prod-us-east',
  },
  {
    event_id: 'st-ev-20260606-ghi789',
    source: 'axway_securetransport',
    timestamp: formatISO(addMinutes(now, -18)),
    transfer_id: 'tr-98763',
    status: 'success',
    file_name: 'outbound/invoices_20260606.pdf',
    file_size_bytes: 2104589,
    duration_ms: 15000,
    protocol: 'FTPS',
    source_host: 'st-node-01.prod',
    target_folder: '/outbound/invoices/',
    account: 'internal_finance',
    node: 'st-node-01.prod',
    cluster: 'prod-us-east',
  },
  {
    event_id: 'st-ev-20260606-jkl012',
    source: 'axway_securetransport',
    timestamp: formatISO(addMinutes(now, -25)),
    transfer_id: 'tr-98762',
    status: 'success',
    file_name: 'inbound/claims_20260606.json',
    file_size_bytes: 567892,
    duration_ms: 8000,
    protocol: 'HTTPS',
    source_host: 'insurance-partner-api.com',
    target_folder: '/inbound/claims/',
    account: 'insurance_partners_llc',
    node: 'st-node-02.prod',
    cluster: 'prod-us-east',
  },
  {
    event_id: 'st-ev-20260606-mno345',
    source: 'axway_securetransport',
    timestamp: formatISO(addMinutes(now, -35)),
    transfer_id: 'tr-98761',
    status: 'failed',
    file_name: 'outbound/reports_20260606.xlsx',
    file_size_bytes: 3421098,
    duration_ms: 45000,
    protocol: 'AS2',
    source_host: 'st-node-04.prod',
    target_folder: '/outbound/reports/',
    account: 'external_auditors',
    error_code: 'ST-ERR-5001',
    error_message: 'Connection timeout to partner endpoint',
    node: 'st-node-04.prod',
    cluster: 'prod-eu-west',
  },
  {
    event_id: 'st-ev-20260606-pqr678',
    source: 'axway_securetransport',
    timestamp: formatISO(addMinutes(now, -42)),
    transfer_id: 'tr-98760',
    status: 'success',
    file_name: 'inbound/transactions_20260606.csv',
    file_size_bytes: 1234567,
    duration_ms: 12000,
    protocol: 'SFTP',
    source_host: 'fintech-partner-02.com',
    target_folder: '/inbound/transactions/',
    account: 'fintech_partners',
    node: 'st-node-01.prod',
    cluster: 'prod-us-east',
  },
  {
    event_id: 'st-ev-20260606-stu901',
    source: 'axway_securetransport',
    timestamp: formatISO(addMinutes(now, -50)),
    transfer_id: 'tr-98759',
    status: 'in_progress',
    file_name: 'outbound/statements_20260606.pdf',
    file_size_bytes: 4567891,
    duration_ms: 0,
    protocol: 'FTPS',
    source_host: 'st-node-02.prod',
    target_folder: '/outbound/statements/',
    account: 'internal_banking',
    node: 'st-node-02.prod',
    cluster: 'prod-us-east',
  },
];

export const mockIncidents: CorrelatedIncident[] = [
  {
    incident_id: 'INC0012345',
    opened_at: formatISO(addMinutes(now, -30)),
    state: 'in_progress',
    assigned_to: 'jane.doe',
    assignment_group: 'MFT Support',
    category: 'File Transfer Failure',
    impact: 2,
    urgency: 2,
    related_transfers: ['tr-98765', 'tr-98764'],
    ci_name: 'axway-st-prod-eus-03',
    severity: 'critical',
  },
  {
    incident_id: 'INC0012344',
    opened_at: formatISO(addHours(now, -2)),
    state: 'resolved',
    assigned_to: 'john.smith',
    assignment_group: 'MFT Support',
    category: 'File Transfer Failure',
    impact: 3,
    urgency: 3,
    related_transfers: ['tr-98750', 'tr-98749'],
    ci_name: 'axway-st-prod-euw-04',
    severity: 'warning',
  },
  {
    incident_id: 'INC0012343',
    opened_at: formatISO(addHours(now, -6)),
    state: 'closed',
    assigned_to: 'jane.doe',
    assignment_group: 'MFT Support',
    category: 'Performance Degradation',
    impact: 3,
    urgency: 2,
    related_transfers: ['tr-98740'],
    ci_name: 'axway-st-prod-eus-01',
    severity: 'info',
  },
];

export const mockNodeHealth: NodeHealth[] = [
  {
    node: 'st-node-01.prod',
    cluster: 'prod-us-east',
    status: 'healthy',
    cpu_percent: 34,
    memory_percent: 52,
    disk_percent: 45,
    queue_depth: 12,
    cert_expiry_days: 120,
    last_seen: formatISO(addMinutes(now, -1)),
  },
  {
    node: 'st-node-02.prod',
    cluster: 'prod-us-east',
    status: 'healthy',
    cpu_percent: 41,
    memory_percent: 58,
    disk_percent: 52,
    queue_depth: 8,
    cert_expiry_days: 95,
    last_seen: formatISO(addMinutes(now, -1)),
  },
  {
    node: 'st-node-03.prod',
    cluster: 'prod-us-east',
    status: 'degraded',
    cpu_percent: 78,
    memory_percent: 82,
    disk_percent: 68,
    queue_depth: 145,
    cert_expiry_days: 7,
    last_seen: formatISO(addMinutes(now, -1)),
  },
  {
    node: 'st-node-04.prod',
    cluster: 'prod-eu-west',
    status: 'critical',
    cpu_percent: 92,
    memory_percent: 89,
    disk_percent: 85,
    queue_depth: 312,
    cert_expiry_days: 2,
    last_seen: formatISO(addMinutes(now, -2)),
  },
  {
    node: 'st-node-05.prod',
    cluster: 'prod-eu-west',
    status: 'maintenance',
    cpu_percent: 12,
    memory_percent: 28,
    disk_percent: 40,
    queue_depth: 0,
    cert_expiry_days: 200,
    last_seen: formatISO(addMinutes(now, -5)),
  },
];

export const mockAnomalyScores: AnomalyScore[] = [
  {
    account: 'partner_bank_inc',
    node: 'st-node-03.prod',
    timestamp: formatISO(addMinutes(now, -5)),
    score: 0.96,
    threshold: 0.85,
    is_anomaly: true,
    metric: 'failure_rate',
    value: 0.15,
    baseline: 0.001,
  },
  {
    account: 'partner_bank_inc',
    node: 'st-node-03.prod',
    timestamp: formatISO(addMinutes(now, -10)),
    score: 0.94,
    threshold: 0.85,
    is_anomaly: true,
    metric: 'failure_rate',
    value: 0.12,
    baseline: 0.001,
  },
  {
    account: 'external_auditors',
    node: 'st-node-04.prod',
    timestamp: formatISO(addMinutes(now, -35)),
    score: 0.87,
    threshold: 0.85,
    is_anomaly: true,
    metric: 'failure_rate',
    value: 0.08,
    baseline: 0.002,
  },
  {
    account: 'fintech_partners',
    node: 'st-node-01.prod',
    timestamp: formatISO(addMinutes(now, -42)),
    score: 0.12,
    threshold: 0.85,
    is_anomaly: false,
    metric: 'failure_rate',
    value: 0.001,
    baseline: 0.001,
  },
  {
    account: 'internal_finance',
    node: 'st-node-01.prod',
    timestamp: formatISO(addMinutes(now, -18)),
    score: 0.08,
    threshold: 0.85,
    is_anomaly: false,
    metric: 'latency_p99',
    value: 18000,
    baseline: 15000,
  },
];

export const mockFailurePredictions: FailurePrediction[] = [
  {
    node: 'st-node-03.prod',
    cluster: 'prod-us-east',
    timestamp: formatISO(now),
    probability: 0.72,
    risk_level: 'high',
    factors: [
      { name: 'Certificate Expiry (days)', value: 7, weight: 0.35 },
      { name: 'Queue Depth', value: 145, weight: 0.25 },
      { name: 'Error Rate Trend (5m)', value: 0.15, weight: 0.2 },
      { name: 'CPU Usage', value: 78, weight: 0.1 },
      { name: 'Memory Usage', value: 82, weight: 0.1 },
    ],
    predicted_within_minutes: 60,
  },
  {
    node: 'st-node-04.prod',
    cluster: 'prod-eu-west',
    timestamp: formatISO(now),
    probability: 0.89,
    risk_level: 'critical',
    factors: [
      { name: 'Certificate Expiry (days)', value: 2, weight: 0.4 },
      { name: 'Queue Depth', value: 312, weight: 0.3 },
      { name: 'Error Rate Trend (5m)', value: 0.22, weight: 0.15 },
      { name: 'Disk Usage', value: 85, weight: 0.1 },
      { name: 'CPU Usage', value: 92, weight: 0.05 },
    ],
    predicted_within_minutes: 30,
  },
  {
    node: 'st-node-01.prod',
    cluster: 'prod-us-east',
    timestamp: formatISO(now),
    probability: 0.12,
    risk_level: 'low',
    factors: [
      { name: 'Certificate Expiry (days)', value: 120, weight: 0.35 },
      { name: 'Queue Depth', value: 12, weight: 0.25 },
      { name: 'Error Rate Trend (5m)', value: 0.001, weight: 0.2 },
      { name: 'CPU Usage', value: 34, weight: 0.1 },
      { name: 'Memory Usage', value: 52, weight: 0.1 },
    ],
    predicted_within_minutes: 120,
  },
];

export const mockBaselineData: BaselineData[] = Array.from({ length: 24 }, (_, i) => {
  const hour = addHours(new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0), i);
  const baseThroughput = 5000 + Math.sin(i * 0.5) * 2000;
  const noise = (Math.random() - 0.5) * 500;
  return {
    timestamp: formatISO(hour),
    actual_throughput: Math.max(0, Math.round(baseThroughput + noise)),
    predicted_lower: Math.round(baseThroughput - 800),
    predicted_upper: Math.round(baseThroughput + 800),
    expected_throughput: Math.round(baseThroughput),
  };
});

export const mockRootCauses: RootCauseCandidate[] = [
  {
    cause: 'SSH Key Expiry on partner-bank-01.external.com',
    score: 0.87,
    evidence: [
      'Error code ST-ERR-4032: SSH key authentication failed',
      'Two consecutive failures for same partner account',
      'Partner certificate expires in 3 days',
    ],
    category: 'certificate',
  },
  {
    cause: 'Firewall rule change blocking port 22',
    score: 0.65,
    evidence: [
      'Change request CHG004521 implemented 2 hours ago',
      'Affected subnet includes partner-bank-01.external.com',
      'Port 22 (SFTP) was modified in rule set',
    ],
    category: 'configuration',
  },
  {
    cause: 'Partner host network unreachable',
    score: 0.42,
    evidence: [
      'Traceroute shows timeout at partner ISP edge',
      'Other partners on same subnet unaffected',
    ],
    category: 'network',
  },
  {
    cause: 'Disk space exhaustion on st-node-03',
    score: 0.31,
    evidence: [
      'Disk usage at 68% (threshold 70%)',
      'Queue depth growing rapidly',
    ],
    category: 'capacity',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alt-001',
    timestamp: formatISO(addMinutes(now, -3)),
    severity: 'critical',
    title: 'Anomaly Detected: partner_bank_inc failure rate spike',
    description: 'Failure rate jumped from 0.1% to 15% in 5 minutes. Model score: 0.96',
    source: 'ml_model',
    acknowledged: false,
    related_transfers: ['tr-98765', 'tr-98764'],
    incident_id: 'INC0012345',
  },
  {
    id: 'alt-002',
    timestamp: formatISO(addMinutes(now, -32)),
    severity: 'critical',
    title: 'Node st-node-04.prod predicted failure within 30 minutes',
    description: 'XGBoost model predicts 89% probability of transfer failures. Cert expires in 2 days, queue depth 312.',
    source: 'ml_model',
    acknowledged: false,
    incident_id: 'INC0012346',
  },
  {
    id: 'alt-003',
    timestamp: formatISO(addMinutes(now, -38)),
    severity: 'warning',
    title: 'Baseline deviation: Throughput 40% below expected',
    description: 'Actual throughput 3,200 vs expected 5,400 transfers/hour. Possible capacity issue.',
    source: 'ml_model',
    acknowledged: true,
  },
  {
    id: 'alt-004',
    timestamp: formatISO(addHours(now, -1)),
    severity: 'info',
    title: 'Single transfer failure: tr-98761',
    description: 'Connection timeout to partner endpoint (ST-ERR-5001). Non-anomalous.',
    source: 'axway_st',
    acknowledged: true,
  },
  {
    id: 'alt-005',
    timestamp: formatISO(addHours(now, -3)),
    severity: 'maintenance',
    title: 'Change window active: st-node-05.prod',
    description: 'Scheduled maintenance CHG004530 in progress. Alerts suppressed.',
    source: 'servicenow',
    acknowledged: true,
  },
];

export const mockMetricCards: MetricCard[] = [
  { title: 'Global Success Rate', value: '99.87%', change: -0.13, changeLabel: 'vs 1h ago', status: 'good', icon: 'check-circle' },
  { title: 'Active Transfers', value: 147, change: 12, changeLabel: 'vs 1h ago', status: 'good', icon: 'activity' },
  { title: 'Open Incidents', value: 3, change: 1, changeLabel: 'vs 1h ago', status: 'warning', icon: 'alert-triangle' },
  { title: 'Nodes Degraded', value: 2, change: 1, changeLabel: 'vs 1h ago', status: 'critical', icon: 'server' },
];

export const mockErrorCodes: ErrorCodeDistribution[] = [
  { code: 'ST-ERR-4032', count: 47, description: 'SSH key authentication failed' },
  { code: 'ST-ERR-5001', count: 23, description: 'Connection timeout to partner endpoint' },
  { code: 'ST-ERR-3015', count: 12, description: 'Disk quota exceeded on target' },
  { code: 'ST-ERR-2008', count: 8, description: 'Protocol version mismatch' },
  { code: 'ST-ERR-1042', count: 5, description: 'Invalid file format' },
];

export const mockAccountHealth: AccountHealth[] = [
  { account: 'partner_bank_inc', total_transfers: 1247, success_rate: 0.85, avg_latency_ms: 32000, anomaly_score: 0.96, status: 'critical' },
  { account: 'external_auditors', total_transfers: 89, success_rate: 0.92, avg_latency_ms: 45000, anomaly_score: 0.87, status: 'degraded' },
  { account: 'fintech_partners', total_transfers: 3421, success_rate: 0.999, avg_latency_ms: 11000, anomaly_score: 0.12, status: 'healthy' },
  { account: 'internal_finance', total_transfers: 567, success_rate: 1.0, avg_latency_ms: 15000, anomaly_score: 0.08, status: 'healthy' },
  { account: 'insurance_partners_llc', total_transfers: 234, success_rate: 1.0, avg_latency_ms: 8000, anomaly_score: 0.05, status: 'healthy' },
  { account: 'internal_banking', total_transfers: 1890, success_rate: 0.998, avg_latency_ms: 18000, anomaly_score: 0.15, status: 'healthy' },
];

export const mockMTTRData = [
  { week: 'Week 1', mttr_minutes: 45 },
  { week: 'Week 2', mttr_minutes: 38 },
  { week: 'Week 3', mttr_minutes: 52 },
  { week: 'Week 4', mttr_minutes: 41 },
  { week: 'Week 5', mttr_minutes: 35 },
  { week: 'Week 6', mttr_minutes: 29 },
  { week: 'Week 7', mttr_minutes: 33 },
  { week: 'Week 8', mttr_minutes: 27 },
];

export const mockVolumeTrend = [
  { date: '2026-05-01', volume: 42000 },
  { date: '2026-05-08', volume: 45000 },
  { date: '2026-05-15', volume: 43000 },
  { date: '2026-05-22', volume: 47000 },
  { date: '2026-05-29', volume: 51000 },
  { date: '2026-06-05', volume: 49000 },
];